skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dex = "62DpUrFdPDYigC4PJ2iU34Ce6NqVzasrd33nTLc8Wmjj"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
